In [1]:
import numpy as np

In [33]:
x = np.empty([3,3], dtype=int)
print(x)

[[4149262842402738779 4153766442030109281 4144759242775368305]
 [4153766442030109280 4158790770364394495 4151345757230397662]
 [4144759242775368297 4151345757230397654 4147923825727815228]]


In [28]:
x = np.zeros([2, 2], dtype=int)
print(x)

[[0 0]
 [0 0]]


In [35]:
x = np.ones([2], dtype=int)
print(x)

[1 1]


In [42]:
a = np.array([[2, 3], [4, 5], [6, 7]])
print(a)
b = np.zeros_like(a, dtype=float, order='C', shape=[3, 3])
print(b)

[[2 3]
 [4 5]
 [6 7]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
