In [116]:
# 冒泡排序
import numpy as np
nums = np.random.randint(100, size=10)
for i in range(0, len(nums)):
    for j in range(0, len(nums)-i-1):
        if nums[j] > nums[j + 1]:
            nums[j], nums[j+1] = nums[j+1], nums[j]
print(nums)

# 简化版
a = [3 ,1 , 5, 2]
for i in range(len(a)):
    for j in range(i, len(a)):
        if a[i] > a[j]:
            a[i], a[j] = a[j], a[i]
print(a)

[33 39 51 64 65 72 76 91 96 99]


In [126]:
# 选择排序
import numpy as np
nums = np.random.randint(100, size=10)
n = len(nums)
for i in range(n):
    k = i
    for j in range(i+1, n):
        if nums[k] > nums[j]:
            k = j
    if k != i:
        nums[i], nums[k] = nums[k], nums[i]
print(nums)

[14 15 18 39 54 66 71 77 79 91]


In [15]:
# 插入排序
import numpy as np
nums = np.random.randint(100, size=10)
print(nums)
count = len(nums)
for i in range(1, count):
    key = nums[i] # 取出一个数
    j = i - 1 # 指针指向前一个数
    while j >= 0 and nums[j] > key: # 如果前一个数比当前的取出的数大，指针继续向后移动
        nums[j+1] = nums[j]
        j -= 1
    nums[j+1] = key
print(nums)

[22 60 89 57 38 49 76 42  5 39]
[ 5 22 38 39 42 49 57 60 76 89]


In [1]:
a = [3 ,1 , 5, 2]
for i in range(len(a)):
    for j in range(i, len(a)):
        if a[i] > a[j]:
            a[i], a[j] = a[j], a[i]
print(a)

[1, 2, 3, 5]
