In [ ]:
import json

from numpy import dtype
from numpy.matrixlib.defmatrix import matrix
from numpy.testing.print_coercion_tables import print_new_cast_table

# 问题1：
# 1. 解析这个books.json
# 2. 把其中数的一些字段整理出来，比如：书名、作者、出版社、出版日期、价格、
# 3. 使用表格库tabulate打印出来
# 4. 保存表格到json文件
json.dump(books, f, ensure_ascii=False, indent=4)


In [59]:
import numpy as np

arr_a = np.array([[1, 2], [4, 5]])
arr_b = np.array([1, 1])
print(arr_a.sum())
print(arr_a.mean())


print(arr_a)




12
3.0
[[0.39970342 0.9978982  0.08397266]
 [0.54382851 0.60341013 0.70392634]
 [0.41262805 0.73502258 0.61831881]]
